services:
  bot:
    build:
      context: .
      target: development
    container_name: licensy-bot-dev
    restart: unless-stopped
    network_mode: "host"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      CLIENT_ID: ${CLIENT_ID}
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules
    command: sh -c "pnpm prisma migrate deploy && pnpm run start"
